export const PLANS = {
  trial: {
    name: 'Free Trial',
    price: 0,
    queries: 50,
    duration: 14,
    stripePriceId: null,
  },
  starter: {
    name: 'Starter',
    priceEur: 29,
    priceWithVat: 35.67,
    queries: 200,
    stripePriceId: process.env.STRIPE_STARTER_PRICE_ID,
    features: [
      '200 queries per month',
      '1 user',
      'Email support',
      'AI Interview System',
      'Conversation history',
    ],
  },
  pro: {
    name: 'Pro',
    priceEur: 79,
    priceWithVat: 97.17,
    queries: -1,
    stripePriceId: process.env.STRIPE_PRO_PRICE_ID,
    features: [
      'Unlimited queries',
      '1 user',
      'Priority support',
      'Advanced AI features',
      'Saved responses',
      'API access',
    ],
  },
  white_label_early_bird: {
    name: 'Early Bird White Label',
    priceEur: 249,
    priceWithVat: 306.27,
    setupFee: 500,
    queries: -1,
    maxSpots: 100,
    stripePriceId: process.env.STRIPE_WHITE_LABEL_EARLY_BIRD_PRICE_ID,
    features: [
      'All White Label features',
      'LIMITED: 100 businesses only',
      'Custom logo + brand colors',
      'Custom subdomain',
      'Agency admin dashboard',
      'Unlimited users',
      'Dedicated support',
      '1 hour onboarding call',
    ],
  },
  white_label: {
    name: 'White Label',
    priceEur: 349,
    priceWithVat: 429.27,
    setupFee: 750,
    queries: -1,
    stripePriceId: process.env.STRIPE_WHITE_LABEL_PRICE_ID,
    features: [
      'Custom logo + brand colors',
      'Custom subdomain',
      'Agency admin dashboard',
      'Unlimited users',
      'Dedicated support',
      '1 hour onboarding call',
    ],
  },
};

export type PlanKey = keyof typeof PLANS;
